In [131]:
import entropy as et
import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
#test code with toy samples

In [7]:
p1 = np.array([[0.1, 0.2, 0.7], [0.3, 0.3, 0.4]])


In [64]:
et.jensen_shannon_divergence(p1)

array([ 0.07489356])

In [124]:
test1 = 'We have sworn forever'
test2 = 'I too have sworn an oath'

In [126]:
vectorizer = CountVectorizer(min_df=1)
test_vector = vectorizer.fit_transform([test1, test2])

In [127]:
print test_vector.toarray()

[[0 1 1 0 1 0 1]
 [1 0 1 1 1 1 0]]


In [128]:
vectorizer.vocabulary_

{u'an': 0,
 u'forever': 1,
 u'have': 2,
 u'oath': 3,
 u'sworn': 4,
 u'too': 5,
 u'we': 6}

In [129]:
size = test_vector.shape[0] * test_vector.shape[1]
test_vector = test_vector/float(size)
test_vector = test_vector.toarray()

In [130]:
jsd = et.jensen_shannon_divergence(test_vector)
jsd

array([ 0.17857143])

In [160]:
vectorizer = TfidfVectorizer(min_df=1)
test_vector = vectorizer.fit_transform([test1,test2])
test_vector.toarray()

array([[ 0.        ,  0.57615236,  0.40993715,  0.        ,  0.40993715,
         0.        ,  0.57615236],
       [ 0.49922133,  0.        ,  0.35520009,  0.49922133,  0.35520009,
         0.49922133,  0.        ]])

In [163]:
vectorizer = TfidfVectorizer(min_df=1, norm = 'l1')
test_vector = vectorizer.fit_transform([test1,test2])
test_vector.toarray()

array([[ 0.        ,  0.29213999,  0.20786001,  0.        ,  0.20786001,
         0.        ,  0.29213999],
       [ 0.22609005,  0.        ,  0.16086493,  0.22609005,  0.16086493,
         0.22609005,  0.        ]])

In [133]:
test_vector.toarray()

array([[ 0.        ,  0.57615236,  0.40993715,  0.        ,  0.40993715,
         0.        ,  0.57615236],
       [ 0.49922133,  0.        ,  0.35520009,  0.49922133,  0.35520009,
         0.49922133,  0.        ]])

In [134]:
vectorizer.vocabulary_

{u'an': 0,
 u'forever': 1,
 u'have': 2,
 u'oath': 3,
 u'sworn': 4,
 u'too': 5,
 u'we': 6}

In [135]:
size = test_vector.shape[0] * test_vector.shape[1]
test_vector = test_vector/float(size)
test_vector = test_vector.toarray()

In [136]:
jsd = et.jensen_shannon_divergence(test_vector)
jsd

array([ 0.09484367])

In [ ]:
#play with some samples from the data

In [222]:
original = pd.read_csv('../data/sherlock_novel.csv')

In [313]:
def calculate_frequency(vector):
    vector = (vector.T/vector.sum(axis=1)).T
    return vector

In [314]:
def jsd(vector):
    return et.jensen_shannon_divergence(vector)

In [322]:
original1 = original.iloc[1]['Text']
original2 = original.iloc[2]['Text']

In [328]:
vectorizer = CountVectorizer(min_df=1)
text_vector = vectorizer.fit_transform([original1, original2]).toarray().astype(float)

In [329]:
text_vector

array([[ 1.,  0.,  1., ...,  0.,  2.,  1.],
       [ 0.,  1.,  0., ...,  1.,  1.,  0.]])

In [331]:
text_vector = calculate_frequency(text_vector)
text_vector

array([[ 0.00035842,  0.        ,  0.00035842, ...,  0.        ,
         0.00071685,  0.00035842],
       [ 0.        ,  0.00043141,  0.        , ...,  0.00043141,
         0.00043141,  0.        ]])

In [340]:
sum(text_vector[1])

0.99999999999999212

In [333]:
jsd(text_vector)

array([ 0.26285872])

In [335]:
vectorizer = TfidfVectorizer(min_df=1)
text_vector =  vectorizer.fit_transform([original1, original2]).toarray().astype(float)

In [336]:
text_vector = calculate_frequency(text_vector)
text_vector

array([[ 0.00046428,  0.        ,  0.00046428, ...,  0.        ,
         0.00066068,  0.00046428],
       [ 0.        ,  0.0005581 ,  0.        , ...,  0.0005581 ,
         0.00039709,  0.        ]])

In [338]:
sum(text_vector[1])

0.99999999999999212

In [339]:
jsd(text_vector)

array([ 0.32105558])